# Generated by Django 2.2.10 on 2022-07-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_four_ssn',
            field=models.CharField(default='test', max_length=11),
            preserve_default=False,
        ),
    ]
