# Generated by Django 2.2.10 on 2022-07-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0002_customuseradmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserAdmin',
        ),
    ]
