# Generated by Django 2.2.10 on 2022-07-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_last_four_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_four_ssn',
            field=models.CharField(max_length=200),
        ),
    ]
