# Generated by Django 2.2.10 on 2022-07-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_customuseradmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ssn',
            field=models.CharField(max_length=20),
        ),
    ]
